name: Install & build contracts & package with hardhat.

runs:
  using: composite

  steps:
    - uses: ./.github/actions/install

    - name: Build contracts
      run: yarn build:hardhat --force # don't use compilation cache
      shell: bash

    - name: Build package
      run: yarn build:pkg
      shell: bash