[profile.default]
names = true
sizes = true
evm_version = "cancun"
fs_permissions = [
    { access = "read", path = "./out/"},
    { access = "read", path = "./config/"}
]
libs = ["lib"]
via-ir = true
optimizer_runs = 999999
ignored_error_codes = ["transient-storage"]

# # enforce compiling tests without via_ir and only some heavy contract with via_ir
# # note: it will only work if tests are using vm.deployCode to deploy contract
additional_compiler_profiles = [ { name = "no-via-ir", via_ir = false } ]
compilation_restrictions = [ { paths = "test/**", via_ir = false } ]

[profile.default.fuzz]
runs = 64

[profile.default.rpc_endpoints]
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

[profile.default.fmt]
wrap_comments = true

[profile.build]
test = "/dev/null"
script = "/dev/null"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
