name: Formatting

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install

      - name: show length of alchemy key
        run: echo ${#ALCHEMY_KEY}
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
