name: Foundry

on:
  push:
    branches:
      - main
  pull_request:

# Allows to skip tests if compilation fails.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-via-ir:
    name: Compilation (via IR)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install

      - name: Build contracts via IR & check sizes
        # don't use compilation cache
        # skip import files, because we don't care if contracts are too big
        run: forge build --force --sizes --skip Import
        env:
          FOUNDRY_PROFILE: build


  test:
    needs: build-via-ir

    name: Local tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chain: [1, 8453]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install-cache

      - name: Run tests on chain ${{ matrix.chain }}
        run: forge test
        env:
           ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
