name: Hardhat

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build contracts & package with hardhat
        uses: ./.github/actions/build-hardhat
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

      - name: Run hardhat tests
        run: yarn test:hardhat
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
