name: Release on NPM

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version to release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true


jobs:
  build-and-deploy:
    name: Build and deploy package
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          submodules: recursive

      - uses: ./.github/actions/install

      - name: Build contracts
        run: yarn build:hardhat --force # don't use compilation cache

      - name: Build package
        run: yarn build:pkg

      - name: Determine version
        id: determine_version
        run: |
          if [ "${{ github.event.inputs.version_type }}" == "major" ]; then
            echo "major"
          elif [ "${{ github.event.inputs.version_type }}" == "minor" ]; then
            echo "minor"
          else
            echo "patch"
          fi
        shell: bash

      - name: Bump package.json version
        run: |
          version_type=$(echo "${{ steps.determine_version.outputs.stdout }}")
          yarn version --${version_type}

      - name: Configure Git User
        run: |
          git config user.name "Morpho Intern"
          git config user.email "intern@morpho.org"

      - name: Push to Correct Branch
        run: |
          git push origin HEAD:${{ github.event.inputs.branch }}
        working-directory: ./path/to/your/package

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn publish --access public

      - name: Create Git Tag
        run: |
          version=$(node -e "console.log(require('./path/to/your/package/package.json').version)")
          git tag -a "v${version}" -m "Release version ${version}"

      - name: Push Git Tag
        run: |
          git push origin "v${version}"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          version=$(node -e "console.log(require('./path/to/your/package/package.json').version)")
          version_type=$(echo "${{ steps.determine_version.outputs.stdout }}")
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"tag_name\":\"v$version\",\"name\":\"Release $version_type $version\",\"body\":\"Release type: $version_type\n\nAdditional release notes can go here.\"}" "https://api.github.com/repos/${{ github.repository }}/releases"
